spring:
  application:
    name: ite-3rd-ecommerce
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${URL}
    username: ${USERNAME}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

